services:
  web-app:
    build:
      context: ./src/web-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./src/web-app/.env
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NUXT_PUBLIC_SUPABASE_URL=http://host.docker.internal:55421
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  