services:
  web-app:
    image: vetzet/web-app
    container_name: web-app
    build:
      context: ./src/web-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./src/web-app/.env
    networks:
      - vetzet-network

networks:
  vetzet-network:
    name: vetzet-network
    driver: bridge
