insert into public.analysis_categories (slug, display_order)
values
  ('alerji-testleri', 1),
  ('ari-xestelikleri', 2),
  ('biyokimyasal-analizler', 2),
  ('diski-analizleri', 3),
  ('endokrinolojik', 4),
  ('genel-kontrol', 5),
  ('qan-analizleri', 6),
  ('hastalik-panelleri', 6),
  ('hematoloji', 7),
  ('hizli-testler', 8),
  ('idrar-analizleri', 9),
  ('ilaclar', 10),
  ('immunoloji', 11),
  ('infeksiyoz', 12),
  ('mikotoksinler', 13),
  ('mikoloji', 13),
  ('mikrobiyoloji', 14),
  ('molekuler-pcr', 15),
  ('organ-panelleri', 16),
  ('parazitoloji', 17),
  ('patoloji', 18),
  ('vitaminler', 19),
  ('yem-testleri', 20),
  ('yun-muayinesi', 21)
on conflict (slug) do update
set display_order = excluded.display_order;

insert into public.analysis_category_translations (category_id, language, name, description)
select c.id, v.language::public.language_code, v.name, null
from public.analysis_categories c
join (
  values
    ('alerji-testleri', 'az', 'Allergiya Testləri'),
    ('alerji-testleri', 'en', 'Allergy Tests'),
    ('alerji-testleri', 'ru', 'Аллергологические тесты'),
    ('ari-xestelikleri', 'az', 'Arı Xəstəlikləri'),
    ('ari-xestelikleri', 'en', 'Bee Diseases'),
    ('ari-xestelikleri', 'ru', 'Болезни пчел'),
    ('biyokimyasal-analizler', 'az', 'Biokimyəvi Analizlər'),
    ('biyokimyasal-analizler', 'en', 'Biochemical Analyses'),
    ('biyokimyasal-analizler', 'ru', 'Биохимические анализы'),
    ('diski-analizleri', 'az', 'Nəcis Analizləri'),
    ('diski-analizleri', 'en', 'Fecal Analyses'),
    ('diski-analizleri', 'ru', 'Анализы кала'),
    ('endokrinolojik', 'az', 'Endokrinoloji Analizlər'),
    ('endokrinolojik', 'en', 'Endocrinology Analyses'),
    ('endokrinolojik', 'ru', 'Эндокринологические анализы'),
    ('genel-kontrol', 'az', 'Ümumi Nəzarət Panelləri'),
    ('genel-kontrol', 'en', 'General Checkup Panels'),
    ('genel-kontrol', 'ru', 'Панели общего контроля'),
    ('qan-analizleri', 'az', 'Qan Analizləri'),
    ('qan-analizleri', 'en', 'Blood Tests'),
    ('qan-analizleri', 'ru', 'Анализы крови'),
    ('hastalik-panelleri', 'az', 'Xəstəlik Panelləri'),
    ('hastalik-panelleri', 'en', 'Disease Panels'),
    ('hastalik-panelleri', 'ru', 'Панели заболеваний'),
    ('hematoloji', 'az', 'Hematoloji'),
    ('hematoloji', 'en', 'Hematology'),
    ('hematoloji', 'ru', 'Гематология'),
    ('hizli-testler', 'az', 'Sürətli Testlər'),
    ('hizli-testler', 'en', 'Rapid Tests'),
    ('hizli-testler', 'ru', 'Экспресс-тесты'),
    ('idrar-analizleri', 'az', 'Sidik Analizləri'),
    ('idrar-analizleri', 'en', 'Urinalysis'),
    ('idrar-analizleri', 'ru', 'Анализы мочи'),
    ('ilaclar', 'az', 'Dərmanlar'),
    ('ilaclar', 'en', 'Drugs'),
    ('ilaclar', 'ru', 'Лекарственные препараты'),
    ('immunoloji', 'az', 'İmmunologiya — Otoimmün Xəstəliklər'),
    ('immunoloji', 'en', 'Immunology - Autoimmune Diseases'),
    ('immunoloji', 'ru', 'Иммунология - аутоиммунные заболевания'),
    ('infeksiyoz', 'az', 'İnfeksion Xəstəliklər'),
    ('infeksiyoz', 'en', 'Infectious Diseases'),
    ('infeksiyoz', 'ru', 'Инфекционные заболевания'),
    ('mikotoksinler', 'az', 'Mikotoksinlər'),
    ('mikotoksinler', 'en', 'Mycotoxins'),
    ('mikotoksinler', 'ru', 'Микотоксины'),
    ('mikoloji', 'az', 'Mikoloji'),
    ('mikoloji', 'en', 'Mycology'),
    ('mikoloji', 'ru', 'Микология'),
    ('mikrobiyoloji', 'az', 'Mikrobiologiya'),
    ('mikrobiyoloji', 'en', 'Microbiology'),
    ('mikrobiyoloji', 'ru', 'Микробиология'),
    ('molekuler-pcr', 'az', 'Molekulyar Analizlər (Real Time PCR)'),
    ('molekuler-pcr', 'en', 'Molecular Analyses (Real-Time PCR)'),
    ('molekuler-pcr', 'ru', 'Молекулярные анализы (Real-Time PCR)'),
    ('organ-panelleri', 'az', 'Orqan Panelləri'),
    ('organ-panelleri', 'en', 'Organ Panels'),
    ('organ-panelleri', 'ru', 'Панели органов'),
    ('parazitoloji', 'az', 'Parazitologiya'),
    ('parazitoloji', 'en', 'Parasitology'),
    ('parazitoloji', 'ru', 'Паразитология'),
    ('patoloji', 'az', 'Patoloji'),
    ('patoloji', 'en', 'Pathology'),
    ('patoloji', 'ru', 'Патология'),
    ('vitaminler', 'az', 'Vitaminlər'),
    ('vitaminler', 'en', 'Vitamins'),
    ('vitaminler', 'ru', 'Витамины'),
    ('yem-testleri', 'az', 'Yem Testləri'),
    ('yem-testleri', 'en', 'Feed Tests'),
    ('yem-testleri', 'ru', 'Анализы кормов'),
    ('yun-muayinesi', 'az', 'Yunun Müayinəsi'),
    ('yun-muayinesi', 'en', 'Wool Testing'),
    ('yun-muayinesi', 'ru', 'Исследование шерсти')
) as v(slug, language, name)
  on v.slug = c.slug
on conflict (category_id, language) do update
set name = excluded.name,
    updated_at = now();
