insert into public.analysis_methods (slug, display_order)
values
  ('elisa', 1),
  ('bakterioloji', 2),
  ('idexx-testi', 3),
  ('nir', 4),
  ('vizual', 5),
  ('halr', 6),
  ('iso-3593', 7),
  ('ilkin-diaqnoz-patoloji-baxis', 8)
on conflict (slug) do update
set display_order = excluded.display_order;

insert into public.analysis_method_translations (method_id, language, name, description)
select m.id, v.language::public.language_code, v.name, v.description
from public.analysis_methods m
join (
  values
    ('elisa', 'az', 'ELISA', null),
    ('elisa', 'en', 'ELISA', null),
    ('elisa', 'ru', 'ELISA', null),
    ('bakterioloji', 'az', 'Bakterioloji', null),
    ('bakterioloji', 'en', 'Bacteriological', null),
    ('bakterioloji', 'ru', 'Бактериологический', null),
    ('idexx-testi', 'az', 'IDEXX-testi', null),
    ('idexx-testi', 'en', 'IDEXX test', null),
    ('idexx-testi', 'ru', 'Тест IDEXX', null),
    ('nir', 'az', 'NIR', null),
    ('nir', 'en', 'NIR', null),
    ('nir', 'ru', 'NIR', null),
    ('vizual', 'az', 'Vizual', null),
    ('vizual', 'en', 'Visual', null),
    ('vizual', 'ru', 'Визуальный', null),
    ('halr', 'az', 'HALR', null),
    ('halr', 'en', 'HALR', null),
    ('halr', 'ru', 'HALR', null),
    ('iso-3593', 'az', 'ISO 3593', null),
    ('iso-3593', 'en', 'ISO 3593', null),
    ('iso-3593', 'ru', 'ISO 3593', null),
    ('ilkin-diaqnoz-patoloji-baxis', 'az', 'İlkin diaqnoz və pataloqo anatomik baxış', null),
    ('ilkin-diaqnoz-patoloji-baxis', 'en', 'Initial diagnosis and pathological anatomical examination', null),
    ('ilkin-diaqnoz-patoloji-baxis', 'ru', 'Первичная диагностика и патолого-анатомический осмотр', null)
) as v(slug, language, name, description)
  on v.slug = m.slug
on conflict (method_id, language) do update
set name = excluded.name,
    description = excluded.description,
    updated_at = now();

insert into public.sample_types (slug, display_order)
values
  ('bal', 1),
  ('ari', 2),
  ('qan-serumu', 3),
  ('qan-serum-plazma', 4),
  ('sud', 5),
  ('yaxma-sud-patoloji-material-etraf-muhit', 6),
  ('patoloji-material', 7),
  ('xammal-yem', 8),
  ('qan-serum', 9),
  ('cirkli-yuyulmus-yun', 10),
  ('teze-qirxilmis-cirkli-yun', 11),
  ('cirkli-yun', 12),
  ('cirkli-yuyulmamis-yun', 13),
  ('mermer-tozu', 14)
on conflict (slug) do update
set display_order = excluded.display_order;

insert into public.sample_type_translations (sample_type_id, language, name, description)
select st.id, v.language::public.language_code, v.name, v.description
from public.sample_types st
join (
  values
    ('bal', 'az', 'Bal', null),
    ('bal', 'en', 'Honey', null),
    ('bal', 'ru', 'Мед', null),
    ('ari', 'az', 'Arı', null),
    ('ari', 'en', 'Bee', null),
    ('ari', 'ru', 'Пчела', null),
    ('qan-serumu', 'az', 'Qan serumu', null),
    ('qan-serumu', 'en', 'Blood serum', null),
    ('qan-serumu', 'ru', 'Сыворотка крови', null),
    ('qan-serum-plazma', 'az', 'Qan/serum/plazma', null),
    ('qan-serum-plazma', 'en', 'Blood/serum/plasma', null),
    ('qan-serum-plazma', 'ru', 'Кровь/сыворотка/плазма', null),
    ('sud', 'az', 'Süd', null),
    ('sud', 'en', 'Milk', null),
    ('sud', 'ru', 'Молоко', null),
    ('yaxma-sud-patoloji-material-etraf-muhit', 'az', 'Yaxma/süd/patoloji material/ətraf mühit', null),
    ('yaxma-sud-patoloji-material-etraf-muhit', 'en', 'Swab/milk/pathological material/environment', null),
    ('yaxma-sud-patoloji-material-etraf-muhit', 'ru', 'Мазок/молоко/патологический материал/окружающая среда', null),
    ('patoloji-material', 'az', 'Patoloji material', null),
    ('patoloji-material', 'en', 'Pathological material', null),
    ('patoloji-material', 'ru', 'Патологический материал', null),
    ('xammal-yem', 'az', 'Xammal/yem', null),
    ('xammal-yem', 'en', 'Raw material/feed', null),
    ('xammal-yem', 'ru', 'Сырье/корм', null),
    ('qan-serum', 'az', 'Qan/serum', null),
    ('qan-serum', 'en', 'Blood/serum', null),
    ('qan-serum', 'ru', 'Кровь/сыворотка', null),
    ('cirkli-yuyulmus-yun', 'az', 'Çirkli yuyulmuş yun', null),
    ('cirkli-yuyulmus-yun', 'en', 'Dirty washed wool', null),
    ('cirkli-yuyulmus-yun', 'ru', 'Грязная промытая шерсть', null),
    ('teze-qirxilmis-cirkli-yun', 'az', 'Təzə qırxılmış çirkli yun', null),
    ('teze-qirxilmis-cirkli-yun', 'en', 'Freshly shorn dirty wool', null),
    ('teze-qirxilmis-cirkli-yun', 'ru', 'Свежестриженная грязная шерсть', null),
    ('cirkli-yun', 'az', 'Çirkli yun', null),
    ('cirkli-yun', 'en', 'Dirty wool', null),
    ('cirkli-yun', 'ru', 'Грязная шерсть', null),
    ('cirkli-yuyulmamis-yun', 'az', 'Çirkli (yuyulmamış) yun', null),
    ('cirkli-yuyulmamis-yun', 'en', 'Dirty unwashed wool', null),
    ('cirkli-yuyulmamis-yun', 'ru', 'Грязная немытая шерсть', null),
    ('mermer-tozu', 'az', 'Mərmər tozu', null),
    ('mermer-tozu', 'en', 'Marble dust', null),
    ('mermer-tozu', 'ru', 'Мраморная пыль', null)
) as v(slug, language, name, description)
  on v.slug = st.slug
on conflict (sample_type_id, language) do update
set name = excluded.name,
    description = excluded.description,
    updated_at = now();

insert into public.analyses (
  slug,
  species_id,
  category_id,
  method_id,
  sample_type_id,
  sample_amount,
  storage_conditions,
  turnaround_time,
  display_order,
  price,
  currency,
  is_active
)
select
  v.slug,
  s.id,
  c.id,
  m.id,
  st.id,
  v.sample_amount,
  v.storage_conditions,
  v.turnaround_time,
  v.display_order,
  v.price,
  'AZN',
  true
from (
  values
    ('bal-orqanoleptiki-ari', 'ari', 'ari-xestelikleri', null, 'bal', '250 ml', 'Plastik/şüşə qablarda', '1 gün', 1, 10.00::numeric),
    ('bal-ph-ari', 'ari', 'ari-xestelikleri', null, 'bal', '250 ml', 'Plastik/şüşə qablarda', '1 gün', 2, 10.00::numeric),
    ('bal-diastaza-ari', 'ari', 'ari-xestelikleri', null, 'bal', '250 ml', 'Plastik/şüşə qablarda', '1 gün', 3, 20.00::numeric),
    ('balin-bakterioloji-muayinesi-ari', 'ari', 'ari-xestelikleri', null, 'bal', '250 ml', 'Plastik/şüşə qablarda', '2-3 gün', 4, 25.00::numeric),
    ('nozema-ari', 'ari', 'ari-xestelikleri', null, 'ari', '5-10 ədəd', 'Plastik/şüşə qablarda', '2-3 gün', 5, 50.00::numeric),
    ('avropa-ve-amerika-curumesi-ari', 'ari', 'ari-xestelikleri', null, 'ari', '5-10 ədəd', 'Plastik/şüşə qablarda', '2-3 gün', 6, 50.00::numeric),
    ('nodulyar-dermatit-mal-qara', 'mal-qara', 'infeksiyoz', 'elisa', 'qan-serumu', '3-5 ml', 'Qan/Soyuq halda serum-24 saat ərzində', '1-2 gün', 10, 25.00::numeric),
    ('dabaq-nsp-mal-qara', 'mal-qara', 'infeksiyoz', 'elisa', 'qan-serumu', '3-5 ml', 'Qan/Soyuq halda serum-24 saat ərzində', '1-2 gün', 11, 25.00::numeric),
    ('dabaq-sp-vaksinasiya-effektivliyi-mal-qara', 'mal-qara', 'infeksiyoz', 'elisa', 'qan-serumu', '3-5 ml', 'Qan/Soyuq halda serum-24 saat ərzində', '1-2 gün', 12, 25.00::numeric),
    ('viruslu-diareya-mal-qara', 'mal-qara', 'infeksiyoz', 'elisa', 'qan-serumu', '3-5 ml', 'Qan/Soyuq halda serum-24 saat ərzində', '1-2 gün', 13, 25.00::numeric),
    ('ibr-viruslu-diareya-neospora-xlamidioz-paketi-mal-qara', 'mal-qara', 'infeksiyoz', 'elisa', 'qan-serumu', '3-5 ml', 'Hemolizə yol vermədən, zərdab ayrılmalı və soyuq çatdırılmalıdır.', '1 gün', 13, 1200.00::numeric),
    ('parainfluenza-mal-qara', 'mal-qara', 'infeksiyoz', 'elisa', 'qan-serumu', '3-5 ml', 'Qan/Soyuq halda serum-24 saat ərzində', '1-2 gün', 14, 25.00::numeric),
    ('smallenberq-mal-qara', 'mal-qara', 'infeksiyoz', 'elisa', 'qan-serumu', '3-5 ml', 'Qan/Soyuq halda serum-24 saat ərzində', '1-2 gün', 15, 25.00::numeric),
    ('bruselyoz-mal-qara', 'mal-qara', 'infeksiyoz', 'elisa', 'qan-serumu', '3-5 ml', 'Qan/Soyuq halda serum-24 saat ərzində', '1-2 gün', 16, 25.00::numeric),
    ('ibr-rinotraxeit-mal-qara', 'mal-qara', 'infeksiyoz', 'elisa', 'qan-serumu', '3-5 ml', 'Qan/Soyuq halda serum-24 saat ərzində', '1-2 gün', 17, 30.00::numeric),
    ('leykoz-mal-qara', 'mal-qara', 'infeksiyoz', 'elisa', 'qan-serumu', '3-5 ml', 'Qan/Soyuq halda serum-24 saat ərzində', '1-2 gün', 18, 25.00::numeric),
    ('neospora-mal-qara', 'mal-qara', 'infeksiyoz', 'elisa', 'qan-serumu', '3-5 ml', 'Qan/Soyuq halda serum-24 saat ərzində', '1-2 gün', 19, 30.00::numeric),
    ('xlamidioz-mal-qara', 'mal-qara', 'infeksiyoz', 'elisa', 'qan-serumu', '3-5 ml', 'Qan/Soyuq halda serum-24 saat ərzində', '1-2 gün', 20, 25.00::numeric),
    ('m-bovis-mal-qara', 'mal-qara', 'infeksiyoz', 'elisa', 'qan-serumu', '3-5 ml', 'Qan/Soyuq halda serum-24 saat ərzində', '1-2 gün', 21, 25.00::numeric),
    ('bogazliq-testi-mal-qara', 'mal-qara', 'genel-kontrol', 'idexx-testi', 'qan-serum-plazma', '3-5 ml', 'Soyuq halda serum-24 saat ərzində', '1 gün', 22, 20.00::numeric),
    ('sudde-antibiotik-teyini-mal-qara', 'mal-qara', 'genel-kontrol', 'idexx-testi', 'sud', '3-5 ml', 'Soyuq halda serum-6 saat ərzində', '1 gün', 23, 20.00::numeric),
    ('ketoz-testi-mal-qara', 'mal-qara', 'genel-kontrol', null, 'qan-serum-plazma', '3-5 ml', null, null, 24, null),
    ('dezinfeksiyanin-effektivliyinin-teyini-mal-qara', 'mal-qara', 'mikrobiyoloji', 'bakterioloji', 'yaxma-sud-patoloji-material-etraf-muhit', '5 nümunə', null, null, 25, null),
    ('antibiogram-mal-qara', 'mal-qara', 'mikrobiyoloji', 'bakterioloji', 'yaxma-sud-patoloji-material-etraf-muhit', '100-200 qr', '+4C/qısa müddətə', '2-3 gün', 30, 50.00::numeric),
    ('patogen-bakteriyalar-mal-qara', 'mal-qara', 'mikrobiyoloji', 'bakterioloji', 'yaxma-sud-patoloji-material-etraf-muhit', '100-200 qr', '+4C/qısa müddətə', '2-3 gün', 31, 25.00::numeric),
    ('e-coli-o157-mal-qara', 'mal-qara', 'mikrobiyoloji', 'bakterioloji', 'yaxma-sud-patoloji-material-etraf-muhit', '100-200 qr', '+4C/qısa müddətə', '2-3 gün', 32, 25.00::numeric),
    ('salmonella-spp-mal-qara', 'mal-qara', 'mikrobiyoloji', 'bakterioloji', 'yaxma-sud-patoloji-material-etraf-muhit', '100-200 qr', '+4C/qısa müddətə', '2-3 gün', 33, 25.00::numeric),
    ('mafam-mal-qara', 'mal-qara', 'mikrobiyoloji', 'bakterioloji', 'yaxma-sud-patoloji-material-etraf-muhit', '100-200 qr', '+4C/qısa müddətə', '2-3 gün', 34, 25.00::numeric),
    ('kif-ve-maya-gobelekleri-mal-qara', 'mal-qara', 'mikrobiyoloji', 'bakterioloji', 'yaxma-sud-patoloji-material-etraf-muhit', '100-200 qr', '+4C/qısa müddətə', '2-3 gün', 35, 25.00::numeric),
    ('suyun-tam-analizi-mal-qara', 'mal-qara', 'mikrobiyoloji', 'bakterioloji', 'yaxma-sud-patoloji-material-etraf-muhit', '100-200 ml', '+4C/qısa müddətə', '2-3 gün', 36, 100.00::numeric),
    ('etraf-muhit-numuneleri-mal-qara', 'mal-qara', 'mikrobiyoloji', 'bakterioloji', 'yaxma-sud-patoloji-material-etraf-muhit', '100-200 qr', '+4C/qısa müddətə', '2-3 gün', 37, 25.00::numeric),
    ('yarma-mal-qara', 'mal-qara', 'patoloji', 'ilkin-diaqnoz-patoloji-baxis', 'patoloji-material', null, null, null, 38, null),
    ('zibillik-derecesi-mal-qara', 'mal-qara', 'yem-testleri', 'vizual', 'xammal-yem', '500 qr', 'Düzgün qablaşdırmada', '1 gün', 60, 5.00::numeric),
    ('yem-orqanoleptiki-mal-qara', 'mal-qara', 'yem-testleri', null, 'xammal-yem', '500 qr', 'Düzgün qablaşdırmada', '1 gün', 61, 10.00::numeric),
    ('protein-mal-qara', 'mal-qara', 'yem-testleri', 'nir', 'xammal-yem', '500 qr', 'Düzgün qablaşdırmada', '1 gün', 62, 15.00::numeric),
    ('nemlik-mal-qara', 'mal-qara', 'yem-testleri', 'nir', 'xammal-yem', '500 qr', 'Düzgün qablaşdırmada', '1 gün', 63, 10.00::numeric),
    ('yag-mal-qara', 'mal-qara', 'yem-testleri', 'nir', 'xammal-yem', '500 qr', 'Düzgün qablaşdırmada', '1 gün', 64, 10.00::numeric),
    ('kul-mal-qara', 'mal-qara', 'yem-testleri', 'nir', 'xammal-yem', '500 qr', 'Düzgün qablaşdırmada', '1 gün', 65, 10.00::numeric),
    ('nisasta-mal-qara', 'mal-qara', 'yem-testleri', 'nir', 'xammal-yem', '500 qr', 'Düzgün qablaşdırmada', '1 gün', 66, 10.00::numeric),
    ('seluloza-mal-qara', 'mal-qara', 'yem-testleri', 'nir', 'xammal-yem', '500 qr', 'Düzgün qablaşdırmada', '1 gün', 67, 10.00::numeric),
    ('elementler-mal-qara', 'mal-qara', 'yem-testleri', 'nir', 'xammal-yem', '500 qr', 'Düzgün qablaşdırmada', '1 gün', 68, 15.00::numeric),
    ('amin-tursulari-mal-qara', 'mal-qara', 'yem-testleri', 'nir', 'xammal-yem', '500 qr', 'Düzgün qablaşdırmada', '1 gün', 69, 15.00::numeric),
    ('sudde-aflatoksin-m1-mal-qara', 'mal-qara', 'mikotoksinler', 'elisa', 'sud', '100 ml', 'Təmiz qablaşdırma/konteyner', '1-2 gün', 70, 80.00::numeric),
    ('aflatoxin-b1-mal-qara', 'mal-qara', 'mikotoksinler', 'elisa', 'xammal-yem', '200-500 qr', 'Təmiz qablaşdırma/paket', '1-2 gün', 71, 80.00::numeric),
    ('deoxynivalenol-don-mal-qara', 'mal-qara', 'mikotoksinler', 'elisa', 'xammal-yem', '200-500 qr', 'Təmiz qablaşdırma/paket', '1-2 gün', 72, 80.00::numeric),
    ('zearalenone-zea-mal-qara', 'mal-qara', 'mikotoksinler', 'elisa', 'xammal-yem', '200-500 qr', 'Təmiz qablaşdırma/paket', '1-2 gün', 73, 80.00::numeric),
    ('oxratoxin-a-ota-mal-qara', 'mal-qara', 'mikotoksinler', 'elisa', 'xammal-yem', '200-500 qr', 'Təmiz qablaşdırma/paket', '1-2 gün', 74, 80.00::numeric),
    ('t2-ht2-toxins-mal-qara', 'mal-qara', 'mikotoksinler', 'elisa', 'xammal-yem', '200-500 qr', 'Təmiz qablaşdırma/paket', '1-2 gün', 75, 80.00::numeric),
    ('fuminosin-mal-qara', 'mal-qara', 'mikotoksinler', 'elisa', 'xammal-yem', '200-500 qr', 'Təmiz qablaşdırma/paket', '1-2 gün', 76, 80.00::numeric),
    ('umumi-aflatoxin-mal-qara', 'mal-qara', 'mikotoksinler', 'elisa', 'xammal-yem', '200-500 qr', 'Təmiz qablaşdırma/paket', '1-2 gün', 77, 80.00::numeric),
    ('qan-serumunda-ehtiyat-qelevinin-teyini-mal-qara', 'mal-qara', 'biyokimyasal-analizler', null, 'qan-serumu', null, null, null, 80, 40.00::numeric),
    ('qan-serumunda-kalsiumun-miqdarinin-teyini-mal-qara', 'mal-qara', 'biyokimyasal-analizler', null, 'qan-serumu', null, null, null, 81, 40.00::numeric),
    ('qan-serumunda-qeyri-uzvi-fosforun-teyini-mal-qara', 'mal-qara', 'biyokimyasal-analizler', null, 'qan-serumu', null, null, null, 82, 40.00::numeric),
    ('heyvan-ve-bitki-menseli-yemlerde-perekis-ededinin-teyini-mal-qara', 'mal-qara', 'biyokimyasal-analizler', null, 'xammal-yem', null, null, null, 83, 40.00::numeric),
    ('bugda-ve-bugda-memulatlarinda-tetrametiltiuram-disulfidinin-teyini-mal-qara', 'mal-qara', 'biyokimyasal-analizler', null, 'xammal-yem', null, null, null, 84, 40.00::numeric),
    ('pambiq-mehsullarinda-serbest-ve-asili-hossipolun-teyini-mal-qara', 'mal-qara', 'biyokimyasal-analizler', null, 'xammal-yem', null, null, null, 85, 40.00::numeric),
    ('mermer-tozunda-kalsium-teyini-mal-qara', 'mal-qara', 'biyokimyasal-analizler', null, 'mermer-tozu', null, null, null, 86, 40.00::numeric),
    ('mermer-tozunda-maqnezium-teyini-mal-qara', 'mal-qara', 'biyokimyasal-analizler', null, 'mermer-tozu', null, null, null, 87, 40.00::numeric),
    ('antibiogram-qus', 'qus', 'mikrobiyoloji', 'bakterioloji', 'yaxma-sud-patoloji-material-etraf-muhit', '100-200 qr', '+4C/qısa müddətə', '2-3 gün', 100, 50.00::numeric),
    ('patogen-bakteriyalar-qus', 'qus', 'mikrobiyoloji', 'bakterioloji', 'yaxma-sud-patoloji-material-etraf-muhit', '100-200 qr', '+4C/qısa müddətə', '2-3 gün', 101, 25.00::numeric),
    ('e-coli-o157-qus', 'qus', 'mikrobiyoloji', 'bakterioloji', 'yaxma-sud-patoloji-material-etraf-muhit', '100-200 qr', '+4C/qısa müddətə', '2-3 gün', 102, 25.00::numeric),
    ('salmonella-spp-qus', 'qus', 'mikrobiyoloji', 'bakterioloji', 'yaxma-sud-patoloji-material-etraf-muhit', '100-200 qr', '+4C/qısa müddətə', '2-3 gün', 103, 25.00::numeric),
    ('mafam-qus', 'qus', 'mikrobiyoloji', 'bakterioloji', 'yaxma-sud-patoloji-material-etraf-muhit', '100-200 qr', '+4C/qısa müddətə', '2-3 gün', 104, 25.00::numeric),
    ('kif-ve-maya-gobelekleri-qus', 'qus', 'mikrobiyoloji', 'bakterioloji', 'yaxma-sud-patoloji-material-etraf-muhit', '100-200 qr', '+4C/qısa müddətə', '2-3 gün', 105, 25.00::numeric),
    ('suyun-tam-analizi-qus', 'qus', 'mikrobiyoloji', 'bakterioloji', 'yaxma-sud-patoloji-material-etraf-muhit', '100-200 ml', '+4C/qısa müddətə', '2-3 gün', 106, 100.00::numeric),
    ('etraf-muhit-numuneleri-qus', 'qus', 'mikrobiyoloji', 'bakterioloji', 'yaxma-sud-patoloji-material-etraf-muhit', '100-200 qr', '+4C/qısa müddətə', '2-3 gün', 107, 25.00::numeric),
    ('yarma-qus', 'qus', 'patoloji', 'ilkin-diaqnoz-patoloji-baxis', 'patoloji-material', null, null, null, 108, null),
    ('rota-korona-qus', 'qus', 'qan-analizleri', 'elisa', 'qan-serum', '3-5 ml', null, '1-2 gün', 110, 15.00::numeric),
    ('nyukasl-xesteliyi-elisa-qus', 'qus', 'qan-analizleri', 'elisa', 'qan-serum', '3-5 ml', null, '1-2 gün', 111, 15.00::numeric),
    ('qus-qripi-h9-qus', 'qus', 'qan-analizleri', 'elisa', 'qan-serum', '3-5 ml', null, '1-2 gün', 112, 15.00::numeric),
    ('qus-qripi-h5-qus', 'qus', 'qan-analizleri', 'elisa', 'qan-serum', '3-5 ml', null, '1-2 gün', 113, 15.00::numeric),
    ('qus-qripi-h7-qus', 'qus', 'qan-analizleri', 'elisa', 'qan-serum', '3-5 ml', null, '1-2 gün', 114, 15.00::numeric),
    ('yoluxucu-bronxit-qus', 'qus', 'qan-analizleri', 'elisa', 'qan-serum', '3-5 ml', null, '1-2 gün', 115, 15.00::numeric),
    ('salmonella-pullorum-qus', 'qus', 'qan-analizleri', 'elisa', 'qan-serum', '3-5 ml', null, '1-2 gün', 116, 15.00::numeric),
    ('yoluxucu-bursit-qus', 'qus', 'qan-analizleri', 'elisa', 'qan-serum', '3-5 ml', null, '1-2 gün', 117, 15.00::numeric),
    ('qus-adenovirusu-qus', 'qus', 'qan-analizleri', 'elisa', 'qan-serum', '3-5 ml', null, '1-2 gün', 118, 15.00::numeric),
    ('mikoplazma-mg-qus', 'qus', 'qan-analizleri', 'elisa', 'qan-serum', '3-5 ml', null, '1-2 gün', 119, 15.00::numeric),
    ('mikoplazma-ms-qus', 'qus', 'qan-analizleri', 'elisa', 'qan-serum', '3-5 ml', null, '1-2 gün', 120, 15.00::numeric),
    ('nyukasl-xesteliyi-halr-qus', 'qus', 'qan-analizleri', 'halr', 'qan-serum', '3-5 ml', null, '1-2 gün', 121, 15.00::numeric),
    ('zibillik-derecesi-qus', 'qus', 'yem-testleri', 'vizual', 'xammal-yem', '500 qr', 'Düzgün qablaşdırmada', '1 gün', 130, 5.00::numeric),
    ('yem-orqanoleptiki-qus', 'qus', 'yem-testleri', null, 'xammal-yem', '500 qr', 'Düzgün qablaşdırmada', '1 gün', 131, 10.00::numeric),
    ('protein-qus', 'qus', 'yem-testleri', 'nir', 'xammal-yem', '500 qr', 'Düzgün qablaşdırmada', '1 gün', 132, 15.00::numeric),
    ('nemlik-qus', 'qus', 'yem-testleri', 'nir', 'xammal-yem', '500 qr', 'Düzgün qablaşdırmada', '1 gün', 133, 10.00::numeric),
    ('yag-qus', 'qus', 'yem-testleri', 'nir', 'xammal-yem', '500 qr', 'Düzgün qablaşdırmada', '1 gün', 134, 10.00::numeric),
    ('kul-qus', 'qus', 'yem-testleri', 'nir', 'xammal-yem', '500 qr', 'Düzgün qablaşdırmada', '1 gün', 135, 10.00::numeric),
    ('nisasta-qus', 'qus', 'yem-testleri', 'nir', 'xammal-yem', '500 qr', 'Düzgün qablaşdırmada', '1 gün', 136, 10.00::numeric),
    ('seluloza-qus', 'qus', 'yem-testleri', 'nir', 'xammal-yem', '500 qr', 'Düzgün qablaşdırmada', '1 gün', 137, 10.00::numeric),
    ('elementler-qus', 'qus', 'yem-testleri', 'nir', 'xammal-yem', '500 qr', 'Düzgün qablaşdırmada', '1 gün', 138, 15.00::numeric),
    ('amin-tursulari-qus', 'qus', 'yem-testleri', 'nir', 'xammal-yem', '500 qr', 'Düzgün qablaşdırmada', '1 gün', 139, 15.00::numeric),
    ('sudde-aflatoksin-m1-qus', 'qus', 'mikotoksinler', 'elisa', 'sud', '100 ml', 'Təmiz qablaşdırma/konteyner', '1-2 gün', 140, 80.00::numeric),
    ('aflatoxin-b1-qus', 'qus', 'mikotoksinler', 'elisa', 'xammal-yem', '200-500 qr', 'Təmiz qablaşdırma/paket', '1-2 gün', 141, 80.00::numeric),
    ('deoxynivalenol-don-qus', 'qus', 'mikotoksinler', 'elisa', 'xammal-yem', '200-500 qr', 'Təmiz qablaşdırma/paket', '1-2 gün', 142, 80.00::numeric),
    ('zearalenone-zea-qus', 'qus', 'mikotoksinler', 'elisa', 'xammal-yem', '200-500 qr', 'Təmiz qablaşdırma/paket', '1-2 gün', 143, 80.00::numeric),
    ('oxratoxin-a-ota-qus', 'qus', 'mikotoksinler', 'elisa', 'xammal-yem', '200-500 qr', 'Təmiz qablaşdırma/paket', '1-2 gün', 144, 80.00::numeric),
    ('t2-ht2-toxins-qus', 'qus', 'mikotoksinler', 'elisa', 'xammal-yem', '200-500 qr', 'Təmiz qablaşdırma/paket', '1-2 gün', 145, 80.00::numeric),
    ('fuminosin-qus', 'qus', 'mikotoksinler', 'elisa', 'xammal-yem', '200-500 qr', 'Təmiz qablaşdırma/paket', '1-2 gün', 146, 80.00::numeric),
    ('umumi-aflatoxin-qus', 'qus', 'mikotoksinler', 'elisa', 'xammal-yem', '200-500 qr', 'Təmiz qablaşdırma/paket', '1-2 gün', 147, 80.00::numeric),
    ('umumi-mikrob-sayi-qoyun', 'qoyun', 'yun-muayinesi', null, 'cirkli-yuyulmus-yun', '50-100 qram', 'Steril paketdə', '1-2 gün', 160, 30.00::numeric),
    ('kif-ve-maya-gobelekleri-qoyun', 'qoyun', 'yun-muayinesi', null, 'cirkli-yuyulmus-yun', '50-100 qram', 'Steril paketdə', '1-2 gün', 161, 30.00::numeric),
    ('patogen-bakteriyalar-qoyun', 'qoyun', 'yun-muayinesi', null, 'teze-qirxilmis-cirkli-yun', '50-100 qram', 'Paketdə', '1-2 gün', 162, 30.00::numeric),
    ('kul-ve-torpaq-miqdari-qoyun', 'qoyun', 'yun-muayinesi', 'iso-3593', 'cirkli-yun', '50-100 qram', 'Paketdə', '1-2 gün', 163, 50.00::numeric),
    ('temiz-yun-ciximi-qoyun', 'qoyun', 'yun-muayinesi', null, 'cirkli-yuyulmamis-yun', '200-500 qram', null, '1-2 gün', 164, 35.00::numeric)
) as v(slug, species_slug, category_slug, method_slug, sample_type_slug, sample_amount, storage_conditions, turnaround_time, display_order, price)
join public.species s on s.slug = v.species_slug
join public.analysis_categories c on c.slug = v.category_slug
left join public.analysis_methods m on m.slug = v.method_slug
join public.sample_types st on st.slug = v.sample_type_slug
on conflict (slug) do update
set species_id = excluded.species_id,
    category_id = excluded.category_id,
    method_id = excluded.method_id,
    sample_type_id = excluded.sample_type_id,
    sample_amount = excluded.sample_amount,
    storage_conditions = excluded.storage_conditions,
    turnaround_time = excluded.turnaround_time,
    display_order = excluded.display_order,
    price = excluded.price,
    currency = excluded.currency,
    is_active = excluded.is_active,
    updated_at = now();

insert into public.analysis_translations (analysis_id, language, name, required_material, notes)
select a.id, v.language::public.language_code, v.name, v.required_material, v.notes
from public.analyses a
join (
  values
    ('bal-orqanoleptiki-ari', 'az', 'Orqanoleptiki', 'Bal, 250 ml', null),
    ('bal-ph-ari', 'az', 'pH', 'Bal, 250 ml', null),
    ('bal-diastaza-ari', 'az', 'Diastaza', 'Bal, 250 ml', null),
    ('balin-bakterioloji-muayinesi-ari', 'az', 'Balın Bakterioloji Müayinəsi', 'Bal, 250 ml', null),
    ('nozema-ari', 'az', 'Nozema', 'Arı, 5-10 ədəd', null),
    ('avropa-ve-amerika-curumesi-ari', 'az', 'Avropa və Amerika çürüməsi', 'Arı, 5-10 ədəd', null),
    ('nodulyar-dermatit-mal-qara', 'az', 'Nodulyar dermatit', 'Qan serumu, 3-5 ml', null),
    ('dabaq-nsp-mal-qara', 'az', 'Dabaq NSP', 'Qan serumu, 3-5 ml', null),
    ('dabaq-sp-vaksinasiya-effektivliyi-mal-qara', 'az', 'Dabaq sp-vaksinasiyanın effektivlik dərəcəsini göstərən', 'Qan serumu, 3-5 ml', null),
    ('viruslu-diareya-mal-qara', 'az', 'Viruslu diareya', 'Qan serumu, 3-5 ml', null),
    ('ibr-viruslu-diareya-neospora-xlamidioz-paketi-mal-qara', 'az', 'İBR, viruslu diareya, Neospora və Xlamidioz paketi', 'Qan zərdabı, hər test üçün 3-5 ml', '14 nümunəlik paket. Paketə daxildir: İBR (rinotraxeit) testi, viruslu diareyya təyini, Neospora təyini və xlamidiozun təyini.'),
    ('parainfluenza-mal-qara', 'az', 'Parainfluenza', 'Qan serumu, 3-5 ml', null),
    ('smallenberq-mal-qara', 'az', 'Şmallenberq', 'Qan serumu, 3-5 ml', null),
    ('bruselyoz-mal-qara', 'az', 'Bruselyoz', 'Qan serumu, 3-5 ml', null),
    ('ibr-rinotraxeit-mal-qara', 'az', 'İBR-rinotraxeit', 'Qan serumu, 3-5 ml', null),
    ('leykoz-mal-qara', 'az', 'Leykoz', 'Qan serumu, 3-5 ml', null),
    ('neospora-mal-qara', 'az', 'Neospora', 'Qan serumu, 3-5 ml', null),
    ('xlamidioz-mal-qara', 'az', 'Xlamidioz', 'Qan serumu, 3-5 ml', null),
    ('m-bovis-mal-qara', 'az', 'M.bovis', 'Qan serumu, 3-5 ml', null),
    ('bogazliq-testi-mal-qara', 'az', 'Boğazlıq testi', 'Qan/serum/plazma, 3-5 ml', null),
    ('sudde-antibiotik-teyini-mal-qara', 'az', 'Süddə antibiotic təyini', 'Süd, 3-5 ml', null),
    ('ketoz-testi-mal-qara', 'az', 'Ketoz testi', 'Qan/serum/plazma, 3-5 ml', null),
    ('dezinfeksiyanin-effektivliyinin-teyini-mal-qara', 'az', 'Dezinfeksiyanın effektivliyinin təyini', 'Yaxma/süd/patoloji material/ətraf mühit, 5 nümunə', null),
    ('antibiogram-mal-qara', 'az', 'Antibiogram', 'Yaxma/süd/patoloji material/ətraf mühit, 100-200 qr', null),
    ('patogen-bakteriyalar-mal-qara', 'az', 'Patogen bakteriyalar', 'Yaxma/süd/patoloji material/ətraf mühit, 100-200 qr', null),
    ('e-coli-o157-mal-qara', 'az', 'E. coli O157', 'Yaxma/süd/patoloji material/ətraf mühit, 100-200 qr', null),
    ('salmonella-spp-mal-qara', 'az', 'Salmonella spp.', 'Yaxma/süd/patoloji material/ətraf mühit, 100-200 qr', null),
    ('mafam-mal-qara', 'az', 'Mafam', 'Yaxma/süd/patoloji material/ətraf mühit, 100-200 qr', null),
    ('kif-ve-maya-gobelekleri-mal-qara', 'az', 'Kif və Maya Göbələkləri', 'Yaxma/süd/patoloji material/ətraf mühit, 100-200 qr', null),
    ('suyun-tam-analizi-mal-qara', 'az', 'Suyun tam analizi', 'Yaxma/süd/patoloji material/ətraf mühit, 100-200 ml', null),
    ('etraf-muhit-numuneleri-mal-qara', 'az', 'Ətraf mühit nümunələri', 'Yaxma/süd/patoloji material/ətraf mühit, 100-200 qr', null),
    ('yarma-mal-qara', 'az', 'Yarma', 'Patoloji material', 'İlkin diaqnoz və pataloqo anatomic baxış.'),
    ('zibillik-derecesi-mal-qara', 'az', 'Zibillik dərəcəsi', 'Xammal/yem, 500 qr', null),
    ('yem-orqanoleptiki-mal-qara', 'az', 'Oraqnoleptiki', 'Xammal/yem, 500 qr', null),
    ('protein-mal-qara', 'az', 'Protein', 'Xammal/yem, 500 qr', null),
    ('nemlik-mal-qara', 'az', 'Nəmlik', 'Xammal/yem, 500 qr', null),
    ('yag-mal-qara', 'az', 'Yağ', 'Xammal/yem, 500 qr', null),
    ('kul-mal-qara', 'az', 'Kül', 'Xammal/yem, 500 qr', null),
    ('nisasta-mal-qara', 'az', 'Nişasta', 'Xammal/yem, 500 qr', null),
    ('seluloza-mal-qara', 'az', 'Seluloza', 'Xammal/yem, 500 qr', null),
    ('elementler-mal-qara', 'az', 'Elementlər', 'Xammal/yem, 500 qr', null),
    ('amin-tursulari-mal-qara', 'az', 'Amin turşuları', 'Xammal/yem, 500 qr', null),
    ('sudde-aflatoksin-m1-mal-qara', 'az', 'Süddə aflatoksin M1', 'Süd, 100 ml', null),
    ('aflatoxin-b1-mal-qara', 'az', 'Aflatoxin B1', 'Xammal/yem, 200-500 qr', null),
    ('deoxynivalenol-don-mal-qara', 'az', 'Deaxynivalenol(DON)', 'Xammal/yem, 200-500 qr', null),
    ('zearalenone-zea-mal-qara', 'az', 'Zearalenone (ZEA)', 'Xammal/yem, 200-500 qr', null),
    ('oxratoxin-a-ota-mal-qara', 'az', 'Oxratoxin A (OTA)', 'Xammal/yem, 200-500 qr', null),
    ('t2-ht2-toxins-mal-qara', 'az', 'T-2/HT-2 toxins', 'Xammal/yem, 200-500 qr', null),
    ('fuminosin-mal-qara', 'az', 'Fuminosin', 'Xammal/yem, 200-500 qr', null),
    ('umumi-aflatoxin-mal-qara', 'az', 'Ümumi aflatoxin', 'Xammal/yem, 200-500 qr', null),
    ('qan-serumunda-ehtiyat-qelevinin-teyini-mal-qara', 'az', 'Qan serumunda ehtiyat qələvinin təyini', 'Qan serumu', 'Metabolik asidoz.'),
    ('qan-serumunda-kalsiumun-miqdarinin-teyini-mal-qara', 'az', 'Qan serumunda kalsiumun miqdarının təyini', 'Qan serumu', 'Kalsiumun həddindən artıq çox olması orqanları zəhərləyir.'),
    ('qan-serumunda-qeyri-uzvi-fosforun-teyini-mal-qara', 'az', 'Qan serumunda qeyri-üzvi fosforun təyini', 'Qan serumu', 'Doğuşdan sonrakı hemoqlobinuriya, sonsuzluq və reproduktiv problemlər. Fosfor çatışmayan heyvanlar yem olmayan maddələri yalamağa və yeməyə başlayırlar.'),
    ('heyvan-ve-bitki-menseli-yemlerde-perekis-ededinin-teyini-mal-qara', 'az', 'Heyvan və bitki mənşəli yemlərdə peroksid ədədinin təyini', 'Xammal/yem', 'Yemdəki piy və yağların köhnəlmə və xarab olma dərəcəsini ölçən keyfiyyət və təhlükəsizlik göstəricisidir.'),
    ('bugda-ve-bugda-memulatlarinda-tetrametiltiuram-disulfidinin-teyini-mal-qara', 'az', 'Buğda və buğda məmulatlarında tetrametiltiuram disülfidinin təyini', 'Xammal/yem', 'Tetrametiltiuram disülfid toxum dərmanı kimi istifadə olunan funqisiddir.'),
    ('pambiq-mehsullarinda-serbest-ve-asili-hossipolun-teyini-mal-qara', 'az', 'Pambıq məhsullarında sərbəst və asılı hossipolun təyini', 'Xammal/yem', 'Sərbəst hossipol ən təhlükəli və zəhərli formadır, hüceyrələri birbaşa parçalayır.'),
    ('mermer-tozunda-kalsium-teyini-mal-qara', 'az', 'Mərmər tozunda kalsium təyini', 'Mərmər tozu', 'Mərmər tozunda kalsium karbonatın (CaCO3) kalsium təyini.'),
    ('mermer-tozunda-maqnezium-teyini-mal-qara', 'az', 'Mərmər tozunda maqnezium təyini', 'Mərmər tozu', 'Artıq olduqda zəhərlənmə yaradır.'),
    ('antibiogram-qus', 'az', 'Antibiogram', 'Yaxma/süd/patoloji material/ətraf mühit, 100-200 qr', null),
    ('patogen-bakteriyalar-qus', 'az', 'Patogen bakteriyalar', 'Yaxma/süd/patoloji material/ətraf mühit, 100-200 qr', null),
    ('e-coli-o157-qus', 'az', 'E. coli O157', 'Yaxma/süd/patoloji material/ətraf mühit, 100-200 qr', null),
    ('salmonella-spp-qus', 'az', 'Salmonella spp.', 'Yaxma/süd/patoloji material/ətraf mühit, 100-200 qr', null),
    ('mafam-qus', 'az', 'Mafam', 'Yaxma/süd/patoloji material/ətraf mühit, 100-200 qr', null),
    ('kif-ve-maya-gobelekleri-qus', 'az', 'Kif və Maya Göbələkləri', 'Yaxma/süd/patoloji material/ətraf mühit, 100-200 qr', null),
    ('suyun-tam-analizi-qus', 'az', 'Suyun tam analizi', 'Yaxma/süd/patoloji material/ətraf mühit, 100-200 ml', null),
    ('etraf-muhit-numuneleri-qus', 'az', 'Ətraf mühit nümunələri', 'Yaxma/süd/patoloji material/ətraf mühit, 100-200 qr', null),
    ('yarma-qus', 'az', 'Yarma', 'Patoloji material', 'İlkin diaqnoz və pataloqo anatomic baxış.'),
    ('rota-korona-qus', 'az', 'Rota/korona', 'Qan/serum, 3-5 ml', null),
    ('nyukasl-xesteliyi-elisa-qus', 'az', 'Nyukasl xəstəliyi', 'Qan/serum, 3-5 ml', null),
    ('qus-qripi-h9-qus', 'az', 'Quş qripi H9', 'Qan/serum, 3-5 ml', null),
    ('qus-qripi-h5-qus', 'az', 'Quş qripi H5', 'Qan/serum, 3-5 ml', null),
    ('qus-qripi-h7-qus', 'az', 'Quş qripi H7', 'Qan/serum, 3-5 ml', null),
    ('yoluxucu-bronxit-qus', 'az', 'Yoluxucu bronxit', 'Qan/serum, 3-5 ml', null),
    ('salmonella-pullorum-qus', 'az', 'Salmonella pullorum', 'Qan/serum, 3-5 ml', null),
    ('yoluxucu-bursit-qus', 'az', 'Yoluxucu bursit', 'Qan/serum, 3-5 ml', null),
    ('qus-adenovirusu-qus', 'az', 'Quş adenovirusu', 'Qan/serum, 3-5 ml', null),
    ('mikoplazma-mg-qus', 'az', 'Mikoplazma MG', 'Qan/serum, 3-5 ml', null),
    ('mikoplazma-ms-qus', 'az', 'Mikoplazma Ms', 'Qan/serum, 3-5 ml', null),
    ('nyukasl-xesteliyi-halr-qus', 'az', 'Nyukasl xəstəliyi', 'Qan/serum, 3-5 ml', null),
    ('zibillik-derecesi-qus', 'az', 'Zibillik dərəcəsi', 'Xammal/yem, 500 qr', null),
    ('yem-orqanoleptiki-qus', 'az', 'Oraqnoleptiki', 'Xammal/yem, 500 qr', null),
    ('protein-qus', 'az', 'Protein', 'Xammal/yem, 500 qr', null),
    ('nemlik-qus', 'az', 'Nəmlik', 'Xammal/yem, 500 qr', null),
    ('yag-qus', 'az', 'Yağ', 'Xammal/yem, 500 qr', null),
    ('kul-qus', 'az', 'Kül', 'Xammal/yem, 500 qr', null),
    ('nisasta-qus', 'az', 'Nişasta', 'Xammal/yem, 500 qr', null),
    ('seluloza-qus', 'az', 'Seluloza', 'Xammal/yem, 500 qr', null),
    ('elementler-qus', 'az', 'Elementlər', 'Xammal/yem, 500 qr', null),
    ('amin-tursulari-qus', 'az', 'Amin turşuları', 'Xammal/yem, 500 qr', null),
    ('sudde-aflatoksin-m1-qus', 'az', 'Süddə aflatoksin M1', 'Süd, 100 ml', null),
    ('aflatoxin-b1-qus', 'az', 'Aflatoxin B1', 'Xammal/yem, 200-500 qr', null),
    ('deoxynivalenol-don-qus', 'az', 'Deaxynivalenol(DON)', 'Xammal/yem, 200-500 qr', null),
    ('zearalenone-zea-qus', 'az', 'Zearalenone (ZEA)', 'Xammal/yem, 200-500 qr', null),
    ('oxratoxin-a-ota-qus', 'az', 'Oxratoxin A (OTA)', 'Xammal/yem, 200-500 qr', null),
    ('t2-ht2-toxins-qus', 'az', 'T-2/HT-2 toxins', 'Xammal/yem, 200-500 qr', null),
    ('fuminosin-qus', 'az', 'Fuminosin', 'Xammal/yem, 200-500 qr', null),
    ('umumi-aflatoxin-qus', 'az', 'Ümumi aflatoxin', 'Xammal/yem, 200-500 qr', null),
    ('umumi-mikrob-sayi-qoyun', 'az', 'Ümumi Mikrob Sayı', 'Çirkli yuyulmuş yun, 50-100 qram', null),
    ('kif-ve-maya-gobelekleri-qoyun', 'az', 'Kif və Maya Göbələkləri', 'Çirkli yuyulmuş yun, 50-100 qram', null),
    ('patogen-bakteriyalar-qoyun', 'az', 'Patogen Bakteriyalar (Salmonella, Staphylococcus aureus və s.)', 'Təzə qırxılmış çirkli yun, 50-100 qram', null),
    ('kul-ve-torpaq-miqdari-qoyun', 'az', 'Kül və Torpaq Miqdarı', 'Çirkli yun, 50-100 qram', null),
    ('temiz-yun-ciximi-qoyun', 'az', 'Təmiz Yun Çıxımı', 'Çirkli (yuyulmamış) yun, 200-500 qram', null)
) as v(slug, language, name, required_material, notes)
  on v.slug = a.slug
on conflict (analysis_id, language) do update
set name = excluded.name,
    required_material = excluded.required_material,
    notes = excluded.notes,
    updated_at = now();

insert into public.analysis_species (analysis_id, species_id)
select id, species_id
from public.analyses
on conflict (analysis_id, species_id) do nothing;
